CREATE DATABASE users;
CREATE DATABASE cart;
CREATE DATABASE events;
CREATE DATABASE orders;
CREATE DATABASE organizations;
CREATE DATABASE payments;
CREATE DATABASE refunds;
CREATE DATABASE reviews;
CREATE DATABASE ticketManagement;
CREATE DATABASE tickets;
CREATE DATABASE venues;
CREATE DATABASE notifications;

